import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <main className="flex justify-center flex-1">{children}</main>
        <footer className="flex justify-center text-sm text-muted-foreground p-3">
          Pocketchat © 2023
        </footer>
      </body>
    </html>
  )
}
